import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logout from "../../layoutClient/logout";
import LogIn from "../../layoutClient/login";
import { getServerSession } from "next-auth";
import SideBar from "../../layoutClient/sidebar";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <head>
        <link href="../src/globals.css" rel="stylesheet"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <div className="flex h-24 bg-white shadow-sm">
          <div className="flex w-[15%] pl-10 items-end">
            <p className="text-[32px] font-bold">TODO</p>
          </div>
          <div className="flex w-[85%] items-end ">
            {
              session ? 
              <div className="flex w-[85%] items-end">
                <span className="absolute right-20"><strong>{session.user.username}님</strong></span>
                <Logout/>
              </div>
              : 
              <div className="flex w-[85%] items-end">
                <a className="absolute right-20" href="/user/register">회원가입</a>
                <LogIn/>
              </div>
            } 
          </div>
        </div>
        <div className="flex h-screen">
          <div className="w-[15%] pl-15 pt-5 pb-5 text-left bg-white border-r border-gray-200">
            <SideBar/>
          </div>
          <div className="w-[85%] ">{children}</div>
        </div>
      </body>
    </html>
  );
}
